//import type { NextComponentType, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ReactElement } from "react";
// TODO: rewire translation later
//import { serverSideTranslations } from "next-i18next/serverSideTranslations";
//import { useTranslation } from "next-i18next";
import { NextPageWithLayout } from "../../types";
import { LoginLayout } from "../components/login-layout";
import Image from "next/image";
import backgroundImg from "../../public/images/bg.jpg";

export const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed -z-10 l">
        <Image
          src={backgroundImg}
          alt="Picture of the author"
          className="max-w-100 h-auto w-auto col-start-0 col-end-1 object-cover md:shrink-0 "
        />
      </div>

      <div className="grid grid-cols-2 gap-20 p-10">
        <div className="justify-items-center grid w-96 h-96">
          <p className="absolute text-3xl text-blue top-[200px] text-center items ">
            &apos;Be the Change <br />
            You Want to See in <br />
            the World&apos;
          </p>
          <br />
          <p className=" absolute text-xs text-stone-500y top-[320px]">
            Mahatma Gandhi
          </p>
          <div className="bg-gradient-to-r text-opacity-100 from-cyan-500 via-purple-500 to-pink-500 opacity-40 border-opacity-30 border-black border-8  py-28 rounded-full grid w-96 h-96"></div>
        </div>
        <div className="min-h-full py-12 px-4 sm:px-6 lg:px-8 bg-black rounded-2xl drop-shadow-xl">
          <div className="max-w-md w-full space-y-8">
            <div>
              <p className="text-left text-sm text-white">LOGO</p>
              <h2 className="mt-6 text-left text-2xl text-white">
                YOUR ACTION PLAN TOWARDS ZERO EMISSIONS
              </h2>
              <p className="mt-8 text-left text-sm text-white">LOG IN</p>
            </div>
            <form className="space-y-4" action="#" method="POST">
              <input type="hidden" name="remember" defaultValue="true" />
              <div className="rounded-md shadow-sm space-y-2">
                <div>
                  <label
                    htmlFor="email-address"
                    className="text-xs font-thin text-white"
                  >
                    Email address
                  </label>
                  <input
                    id="email-address"
                    name="email"
                    type="email"
                    autoComplete="email"
                    required
                    className="appearance-none rounded relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-black rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                    placeholder="Email address"
                  />
                </div>
                <div>
                  <label
                    htmlFor="password"
                    className="text-xs font-thin text-white"
                  >
                    Password
                  </label>
                  <input
                    id="password"
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    required
                    className="appearance-none rounded relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-black rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                    placeholder="Password"
                  />
                </div>
              </div>

              <div className="flex items-center justify-end">
                <div className="text-xs">
                  <a
                    href="#"
                    className="font-medium text-white hover:text-indigo-500"
                  >
                    Forgot password?
                  </a>
                </div>
              </div>

              <div className="flex items-center justify-center">
                <button
                  type="submit"
                  className=" 
                relative w-2/3 
                flex justify-center 
                py-2 px-4 
                border border-cyan-400
                text-sm font-medium text-white
                rounded-full bg-black hover:bg-cyan-400 hover:bg-opacity-40 hover:border-opacity-0 hover:text-black"
                >
                  <span className="absolute left-0 inset-y-0 flex items-center pl-3"></span>
                  LOG IN
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

Home.getLayout = function getLayout(children: ReactElement) {
  return <LoginLayout>{children}</LoginLayout>;
};

export default Home;
