import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Footer from "../components/footer";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home"])),
    },
  };
}

export const Home: NextPage = (props) => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="container mx-auto my-6">
        <h1 className=" text-center">{t("home:welcome_msg")}</h1>

        <button className=" bg-blue-500 hover:bg-blue-700 text-white py-4 px-6 rounded">
          <Link href="./boarding">
            <a>{t("home:boarding")}</a>
          </Link>
        </button>
      </div>
    </>
  );
};

export default Home;

Home.getLayout = function PageLayout(page) {
  return (
    <>
      {page}
      <Footer />
    </>
  );
};
